# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f435421e692dd1603074fc1beb16ec1193de80e2f9d26be11e2d8dfe7ddbcc4c3bd2598383a4d94a0cc53a8a63b2e9f0fbe8e35fc6b77ea5d4ec48a9d099592

test:
  secret_key_base: a15fd4cc70df00ecd982a89c7adad24fe96cb123fd94bea99baef0fd389d3c1633081b88b1eff658cee73a72a53b2587ed6e010fb0e9569ed20693b5ff1ed0dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
